### ISSUE TITLE
Conflict with Obsidian Git plugin

### ISSUE THREAD

**Issue by ribber** [isaaclyman/novel-word-count-obsidian#102]
Before install this Plugin

![image](https://github.com/user-attachments/assets/3674d7c0-a5be-497f-b911-03ca9b418c20)

After install this Plugin

![image](https://github.com/user-attachments/assets/8b756625-fabf-4336-83e7-719bbff9b0ac)

**Comment by isaaclyman** [comment]
Compatibility with every other plugin is not a realistic goal for Novel Word Count.

**Comment by ribber** [comment]
I found the problem is this CSS

```css
.nav-files-container .nav-folder-title::after {
    flex: 1 0 auto;
}

.nav-files-container .nav-file-title::after {
    flex: 1 0 auto;
}
```

This CSS section breaks other plugins，Can you make it only work on the file Explore view?
