### ISSUE TITLE
Change text color?

### ISSUE THREAD

**Issue by greetclammy** [isaaclyman/novel-word-count-obsidian#109]
Hi! 

This isn't a FR nor a bug report. I just wanted to ask how do I change the color of the text added by the plugin to a more muted one via custom CSS? I find the current color too contrasty, which makes my file explorer look busy and cluttered:

<img width="297" alt="Screen Shot 2025-01-08 at 15 03 22" src="https://github.com/user-attachments/assets/227b013b-cb92-494a-850e-47afa7a8cd00" />

I tried to identify the element with the dev tools' element picker to no avail.

Thanks for this plugin! 🙌

**Comment by isaaclyman** [comment]
Hey, sure. There are three selectors you'd need to target. You can find them by looking for the `content: attr(data-novel-word-count-plugin);` rule in the plugin's CSS file.

- For the [vault count](https://github.com/isaaclyman/novel-word-count-obsidian/blob/master/styles.css#L5), target `.novel-word-count--active .nav-header .nav-buttons-container::after`.
- For the [per-file counts](https://github.com/isaaclyman/novel-word-count-obsidian/blob/master/styles.css#L24), target `.novel-word-count--active .nav-files-container .nav-file-title::after`.
- For the [folder counts](https://github.com/isaaclyman/novel-word-count-obsidian/blob/master/styles.css#L67), target `.novel-word-count--active .nav-files-container .nav-folder-title::after`.

**Comment by greetclammy** [comment]
Thank you!

I ended up going with this:
```css
.novel-word-count--active .nav-header .nav-buttons-container::after,
.novel-word-count--active .nav-files-container .nav-file-title::after,
.novel-word-count--active .nav-files-container .nav-folder-title::after {
    opacity: 0.5;
    color: var(--text-muted);
}
```
