### ISSUE TITLE
Pseudo-dynamic colors for differing word counts

### ISSUE THREAD

**Issue by mariomui** [isaaclyman/novel-word-count-obsidian#112]
**Problem**
Currently, the colors are all the same, there's no contrast. You can't easily see which chapters are too small, which chapters are too big--especially in a big vault.

I want multiple colors on the displayed word count, but _dependent_ on the _size_ of the word count.
I currently randomly generate colors using sass.

**Idea**
The idea is to inject the length of the word count into an attribute. So a folder with 300words would have a [data-novel-word-length=3]
This allows a css way of generating the standard colors necessary to differentiate every length without unn. js calculation. This would all be performant pre-processed css as long as the length is pre-injected into the dom. 
data-count="300" data-len="3"
data-count="4844" data-len="4"
data-count="53,443" data-len="5" 
and so on and so forth. 

Since projects are usually 120k-300k in length (300,000)--a built-in upper bound of 6 would suffice for 90% of user needs.

```scss
$three: (
  length: "3",
  color: "--threeColor",
);

// list of lists
$novelmaps: ( 
  $three,
  $two,
  ....
)
@each $novelmap in $novelmaps {
  $length: map-get($novelmap, "length");
  $color: map-get($novelmap, "color");
  &:has(.nav-folder-title[data-novel-word-length="#{$length}"]) {
    color: $color
  }
}
```

Should you not want to implement the scss file as it does create a large css file--just injecting the data-attribute would be enough for a proper test trial. But i do not foresee any performance impact.

Below is a mockup

<img width="133" alt="Image" src="https://github.com/user-attachments/assets/ae4d7d44-2d1c-47ea-93e8-c2ebc5e99dbf" />
