### ISSUE TITLE
Conflict with the Iconize plugin

### ISSUE THREAD

**Issue by S1rDev10us** [isaaclyman/novel-word-count-obsidian#86]
**Description**

When using the [obsidian Iconize](https://github.com/FlorianWoelki/obsidian-iconize) plugin, the icon from that plugin goes onto a different line when changing alignment to below.

With align right
![image](https://github.com/isaaclyman/novel-word-count-obsidian/assets/90798437/68a28759-3bfb-459e-981d-65028cc52212)

With align below
![image](https://github.com/isaaclyman/novel-word-count-obsidian/assets/90798437/2668ed41-56b9-4211-9c52-3b9b351e80ad)

The problem appears to be that when alignment is set to below, flex-wrap is set to wrap which not only wraps the novel word count but also the Iconize icon
[Code link](https://github.com/isaaclyman/novel-word-count-obsidian/blob/ade96aa55e237148234020d354cc97578be48781/styles.scss#L34-L36)
```css
.novel-word-count--folder-below .nav-files-container .nav-folder-title {
    flex-wrap: wrap;
}
```

**Device**

Tested on Windows
